server.port=${PORT:8080}
server.address=0.0.0.0
logging.level.org.atmosphere=warn
# Tell Hibernate which timezone to use when reading/writing LocalDateTime
spring.jpa.properties.hibernate.jdbc.time_zone=America/Los_Angeles

# Launch the default browser when starting the application in development mode
vaadin.launch-browser=false
vaadin.version=25.2.1

# To improve the performance during development.
# For more information https://vaadin.com/docs/latest/flow/integrations/spring/configuration#special-configuration-parameters
vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.example

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=create
pring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
# EXPLICIT driver class name
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

# Reduce maxLifetime to be less than the database's connection timeout
spring.datasource.hikari.maxLifetime=30000 
# spring.datasource.hikari.idleTimeout=300000   
spring.datasource.hikari.connectionTimeout=30000  
spring.datasource.hikari.validationTimeout=5000   
spring.datasource.hikari.leakDetectionThreshold=30000
spring.datasource.hikari.keepalive-time=0    

logging.level.org.springframework.orm.jpa=WARN


  
  




